### ISSUE TITLE
Add pfr_id to players dataset

### ISSUE THREAD

**Issue by alecglen** [nflverse/nflreadr#193] opened 2023-08-04 15:03 UTC
1. **Is your feature request related to a problem? Please describe.**

    Currently you have to join across e.g. rosters or ff_playerids to get from players to pfr_advstats via IDs.

2. **Describe the solution you'd like**

    Add a `pfr_id` column to the dataset returned by `load_players()` to enable a direct join to PFR data.

___

Not a high priority, just a convenience ask if it's not too much effort.

**Comment by mrcaseb** [comment] 2023-08-07 09:41
PFR ID already is on the list of ID we plan to add. Related issue https://github.com/nflverse/nflverse-rosters/issues/72

I am going to close this as it is more or less a duplicate of the above mentioned issue.

**Closed by mrcaseb** 2023-08-07 09:41 UTC
